<?php
	/*
	En mi caso, estos son los datos para la base de datos
	en mi servidor web local. Si los necesitas, pues los
	ajustan si algún dato cambia.
	define('USUARIO','root');
	define('CONTRASENHA','root');
	define('HOST','localhost');
	define('NOMBRE_BD','autoServicio');*/

	/*Estos son los datos del servidor de pecas*/
	define('USUARIO','blackout_afgano1');
	define('CONTRASENHA','mLGFwq#CPG-*');
	define('HOST','72.249.55.76');
	define('NOMBRE_BD','blackout_afganos');
?>